apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: stable-node-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: fixed-percent
  value: "50"
  duration: "30s"
  selector:
    namespaces:
      - mutadev
    labelSelectors:
      chain: "muta"
      chaos: "true"
  scheduler:
    cron: "@every 10m"
