apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: stable-network-duplicate
  namespace: chaos-testing
spec:
  action: duplicate
  mode: fixed-percent
  value: "30"
  selector:
    namespaces:
      - mutadev
    labelSelectors:
      chain: "muta"
      chaos: "true"
  duplicate:
    duplicate: "40"
    correlation: "25"
  duration: "10s"
  scheduler:
    cron: "@every 1m20s"
